# Generated by Django 6.0.6 on 2026-06-17 06:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=500, unique=True)),
                ('articles_json', models.JSONField(default=list)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'news_cache',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('avatar', models.URLField(blank=True, default='', max_length=500)),
                ('platform', models.CharField(choices=[('intergram', 'Intergram'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], default='intergram', max_length=20)),
                ('type', models.CharField(choices=[('direct', 'Direct'), ('group', 'Group'), ('bridge', 'Bridge')], default='direct', max_length=20)),
                ('encryption_key', models.TextField(blank=True, default='')),
                ('last_message', models.TextField(blank=True, default='')),
                ('last_message_time', models.DateTimeField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sender_name', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, default='')),
                ('is_encrypted', models.BooleanField(default=True)),
                ('encryption_key_hash', models.CharField(blank=True, default='', max_length=128)),
                ('file_url', models.URLField(blank=True, default='', max_length=1000)),
                ('file_id', models.CharField(blank=True, default='', max_length=200)),
                ('file_name', models.CharField(blank=True, default='', max_length=300)),
                ('file_type', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], default='', max_length=20)),
                ('file_size', models.CharField(blank=True, default='', max_length=50)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('location_address', models.TextField(blank=True, default='')),
                ('poll_data', models.JSONField(blank=True, null=True)),
                ('checklist_data', models.JSONField(blank=True, null=True)),
                ('contact_info_data', models.JSONField(blank=True, null=True)),
                ('wallet_transfer_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatsession')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InviteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('number', 'Phone Number')], max_length=10)),
                ('recipient', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('invite_link', models.URLField(blank=True, default='', max_length=1000)),
                ('transmission_info', models.CharField(blank=True, default='', max_length=300)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invite_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=100)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(default='Available on Prix', max_length=200)),
                ('is_online', models.BooleanField(default=False)),
                ('allow_google_drive', models.BooleanField(default=False)),
                ('allow_camera', models.BooleanField(default=False)),
                ('allow_audio', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(default='Available', max_length=200)),
                ('is_online', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacted_by', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['name'],
                'unique_together': {('owner', 'email')},
            },
        ),
    ]
